package com.upgrd.recipes.framework;

import com.upgrd.recipes.BulkFileRecipe;
import com.upgrd.recipes.FileRecipe;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Scaffolds a Spring {@code @ControllerAdvice} for Struts {@code ActionForm} → typed form binding.
 */
public final class StrutsFormBindingAdviceScaffoldRecipe implements BulkFileRecipe {

    private StrutsMappingIndex mappingIndex = StrutsMappingIndex.empty();

    @Override
    public void prepare(Path projectRoot) throws IOException {
        mappingIndex = StrutsMappingIndex.loadFromProject(projectRoot);
    }

    @Override
    public List<FileChange> generateChanges(Path projectRoot) throws IOException {
        prepare(projectRoot);
        if (mappingIndex.formBeans().isEmpty()) {
            return List.of();
        }
        String basePackage = inferBasePackage(projectRoot);
        String relativePath = "src/main/java/" + basePackage.replace('.', '/') + "/config/StrutsFormBindingAdvice.java";
        Path target = projectRoot.resolve(relativePath);
        if (Files.isRegularFile(target)) {
            return List.of();
        }
        return List.of(new FileChange(relativePath, "", generateSource(basePackage)));
    }

    @Override
    public String coordinate() {
        return "upgrd:StrutsFormBindingAdvice";
    }

    @Override
    public String displayName() {
        return "Scaffold @ControllerAdvice for Struts form binding";
    }

    @Override
    public Optional<FileChange> transform(String relativePath, String content) {
        return Optional.empty();
    }

    private String inferBasePackage(Path projectRoot) throws IOException {
        try (var walk = Files.walk(projectRoot.resolve("src/main/java"))) {
            return walk.filter(Files::isRegularFile)
                    .filter(p -> p.toString().endsWith("Action.java"))
                    .findFirst()
                    .map(this::packageFromFile)
                    .orElse("com.example");
        } catch (IOException ex) {
            return "com.example";
        }
    }

    private String packageFromFile(Path javaFile) {
        try {
            String content = Files.readString(javaFile);
            int pkg = content.indexOf("package ");
            if (pkg < 0) {
                return "com.example";
            }
            int semi = content.indexOf(';', pkg);
            return content.substring(pkg + 8, semi).trim();
        } catch (IOException ex) {
            return "com.example";
        }
    }

    private String generateSource(String basePackage) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(basePackage).append(".config;\n\n");
        sb.append("""
                import org.springframework.web.bind.WebDataBinder;
                import org.springframework.web.bind.annotation.ControllerAdvice;
                import org.springframework.web.bind.annotation.InitBinder;
                import org.springframework.web.bind.annotation.ModelAttribute;
                """);

        List<String> formImports = new ArrayList<>();
        for (StrutsMappingIndex.FormBean bean : mappingIndex.formBeans().values()) {
            String fqcn = bean.type();
            if (fqcn.contains(".") && !fqcn.contains("DynaActionForm")) {
                formImports.add(fqcn);
            } else {
                String simple = StrutsMappingIndex.inferFormClassName(bean.name());
                formImports.add(basePackage + "." + simple);
            }
        }
        formImports.stream().distinct().sorted().forEach(fqcn -> sb.append("import ").append(fqcn).append(";\n"));
        sb.append("""
                
                /**
                 * Generated by UpGrd — binds Struts form-bean names to typed Spring MVC models.
                 */
                @ControllerAdvice(basePackages = "%s")
                public class StrutsFormBindingAdvice {
                """.formatted(basePackage));

        for (StrutsMappingIndex.FormBean bean : mappingIndex.formBeans().values()) {
            String formName = bean.name();
            String type = resolveSimpleType(bean, basePackage);
            sb.append("""
                
                    @ModelAttribute("%s")
                    public %s %s() {
                        return new %s();
                    }
                """.formatted(formName, type, formName, type));
            sb.append("""
                
                    @InitBinder("%s")
                    public void init%s(WebDataBinder binder) {
                        // UpGrd: migrated from Struts ActionForm — block framework-only properties
                        binder.setDisallowedFields(
                                "class", "multipartRequestHandler", "validator", "servlet", "mapping");
                    }
                """.formatted(formName, capitalize(formName)));
        }
        sb.append("}\n");
        return sb.toString();
    }

    private String resolveSimpleType(StrutsMappingIndex.FormBean bean, String basePackage) {
        String fqcn = bean.type();
        if (fqcn.contains(".") && !fqcn.contains("DynaActionForm")) {
            int dot = fqcn.lastIndexOf('.');
            return fqcn.substring(dot + 1);
        }
        return StrutsMappingIndex.inferFormClassName(bean.name());
    }

    private String capitalize(String value) {
        if (value == null || value.isEmpty()) {
            return value;
        }
        return Character.toUpperCase(value.charAt(0)) + value.substring(1);
    }
}
