package com.upgrd.recipes.framework;

import com.upgrd.recipes.FileRecipe;

import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Scaffolds Thymeleaf HTML templates from Struts JSP views (starter migration).
 */
public final class StrutsJspToThymeleafRecipe implements FileRecipe {

    private static final Pattern STRUTS_JSP = Pattern.compile(
            "(html:|bean:|logic:)[a-zA-Z]+");
    private static final Pattern FORM_ACTION = Pattern.compile(
            "<html:form\\s+action=\"([^\"]+)\"[^>]*>", Pattern.CASE_INSENSITIVE);
    private static final Pattern TEXT_PROPERTY = Pattern.compile(
            "<html:text\\s+property=\"([^\"]+)\"\\s*/?>", Pattern.CASE_INSENSITIVE);
    private static final Pattern SUBMIT = Pattern.compile(
            "<html:submit\\s+value=\"([^\"]+)\"\\s*/?>", Pattern.CASE_INSENSITIVE);
    private static final Pattern BEAN_WRITE = Pattern.compile(
            "<bean:write\\s+name=\"([^\"]+)\"\\s+property=\"([^\"]+)\"\\s*/?>", Pattern.CASE_INSENSITIVE);

    @Override
    public String coordinate() {
        return "upgrd:StrutsJspToThymeleaf";
    }

    @Override
    public String displayName() {
        return "Scaffold Thymeleaf templates from Struts JSP views";
    }

    @Override
    public Optional<FileChange> transform(String relativePath, String content) {
        if (!relativePath.endsWith(".jsp") || !STRUTS_JSP.matcher(content).find()) {
            return Optional.empty();
        }

        String thymeleaf = convertToThymeleaf(content);
        String templatePath = templatePath(relativePath);
        return Optional.of(new FileChange(templatePath, "", thymeleaf));
    }

    private String templatePath(String jspPath) {
        String base = jspPath.replace('\\', '/');
        if (base.startsWith("src/main/webapp/")) {
            base = base.substring("src/main/webapp/".length());
        }
        if (base.endsWith(".jsp")) {
            base = base.substring(0, base.length() - 4);
        }
        return "src/main/resources/templates/" + base + ".html";
    }

    private String convertToThymeleaf(String jsp) {
        String body = jsp;
        body = body.replaceAll("<%@.*?%>", "");
        body = body.replaceAll("<html:html[^>]*>", "<!DOCTYPE html>\n<html xmlns:th=\"http://www.thymeleaf.org\">");
        body = body.replaceAll("</html:html>", "</html>");

        Matcher form = FORM_ACTION.matcher(body);
        if (form.find()) {
            String action = form.group(1);
            body = form.replaceFirst(Matcher.quoteReplacement(
                    "<form th:action=\"@{" + action + "}\" th:object=\"${userForm}\" method=\"post\">"));
        }
        body = body.replaceAll("</html:form>", "</form>");

        Matcher text = TEXT_PROPERTY.matcher(body);
        body = text.replaceAll("<input type=\"text\" th:field=\"*{$1}\"/>");

        Matcher submit = SUBMIT.matcher(body);
        body = submit.replaceAll("<button type=\"submit\" th:text=\"'$1'\">$1</button>");

        Matcher write = BEAN_WRITE.matcher(body);
        body = write.replaceAll("<span th:text=\"\\${$1.$2}\"></span>");

        return """
                <!-- Generated by UpGrd from Struts JSP — review th:object and field names -->
                %s
                """.formatted(body.trim());
    }
}
