package com.upgrd.recipes.framework;

import com.upgrd.recipes.FileRecipe;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Converts Struts 1 {@code struts-config.xml} action mappings into Spring MVC migration hints.
 */
public final class StrutsConfigToSpringRecipe implements FileRecipe {

    private static final Pattern ACTION = Pattern.compile(
            "<action\\s+path=\"([^\"]+)\"\\s+type=\"([^\"]+)\"[^>]*>",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern FORWARD = Pattern.compile(
            "<forward\\s+name=\"([^\"]+)\"\\s+path=\"([^\"]+)\"\\s*/>");

    @Override
    public String coordinate() {
        return "upgrd:StrutsConfigToSpring";
    }

    @Override
    public String displayName() {
        return "Migrate Struts config action mappings to Spring MVC hints";
    }

    @Override
    public Optional<FileChange> transform(String relativePath, String content) {
        if (!relativePath.contains("struts-config") || !relativePath.endsWith(".xml")) {
            return Optional.empty();
        }
        if (!content.contains("<action")) {
            return Optional.empty();
        }

        List<String> mappings = new ArrayList<>();
        Matcher actionMatcher = ACTION.matcher(content);
        while (actionMatcher.find()) {
            String path = actionMatcher.group(1);
            String type = actionMatcher.group(2);
            String forward = findForward(content, actionMatcher.end());
            mappings.add("- `" + path + "` → `" + type + "` → view `" + forward + "`");
        }

        if (mappings.isEmpty()) {
            return Optional.empty();
        }

        String after = springHintsXml(mappings);
        String hintsPath = relativePath.replace("struts-config.xml", "spring-struts-migration.xml");
        return Optional.of(new FileChange(hintsPath, "", after));
    }

    private String findForward(String content, int from) {
        int end = Math.min(content.length(), from + 400);
        Matcher forward = FORWARD.matcher(content.substring(from, end));
        if (forward.find()) {
            return forward.group(2);
        }
        return "(review forward)";
    }

    private String springHintsXml(List<String> mappings) {
        StringBuilder xml = new StringBuilder();
        xml.append("""
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd from struts-config.xml — merge into Spring MVC configuration -->
                <beans xmlns="http://www.springframework.org/schema/beans"
                       xmlns:mvc="http://www.springframework.org/schema/mvc"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="
                         http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
                         http://www.springframework.org/schema/mvc https://www.springframework.org/schema/mvc/spring-mvc.xsd">

                  <!-- UpGrd Struts → Spring MVC mapping hints (review URL patterns and view names):
                """);
        mappings.forEach(m -> xml.append("                  ").append(m).append("\n"));
        xml.append("""
                    -->
                  <mvc:annotation-driven/>
                </beans>
                """);
        return xml.toString();
    }
}
