package com.upgrd.recipes.framework;

import com.upgrd.recipes.BulkFileRecipe;
import com.upgrd.recipes.FileRecipe;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Scaffolds typed Spring MVC form POJOs from Struts {@code form-bean} definitions.
 */
public final class StrutsFormBeanScaffoldRecipe implements BulkFileRecipe {

    private StrutsMappingIndex mappingIndex = StrutsMappingIndex.empty();
    private StrutsValidationIndex validationIndex = StrutsValidationIndex.empty();

    @Override
    public void prepare(Path projectRoot) throws IOException {
        mappingIndex = StrutsMappingIndex.loadFromProject(projectRoot);
        validationIndex = StrutsValidationIndex.loadFromProject(projectRoot);
    }

    @Override
    public List<FileChange> generateChanges(Path projectRoot) throws IOException {
        prepare(projectRoot);
        List<FileChange> changes = new ArrayList<>();
        String defaultPackage = inferDefaultPackage(projectRoot);

        for (StrutsMappingIndex.FormBean bean : mappingIndex.formBeans().values()) {
            String fqcn = resolveFqcn(bean, defaultPackage);
            String relativePath = fqcnToRelativePath(fqcn);
            Path target = projectRoot.resolve(relativePath);
            if (Files.isRegularFile(target)) {
                continue;
            }
            List<StrutsValidationIndex.ValidationField> fields = validationIndex.fieldsFor(bean.name());
            if (fields.isEmpty()) {
                fields = List.of(new StrutsValidationIndex.ValidationField("username", List.of()));
            }
            String source = generateSource(fqcn, bean.name(), fields);
            changes.add(new FileChange(relativePath, "", source));
        }
        return changes;
    }

    @Override
    public String coordinate() {
        return "upgrd:StrutsFormBeanScaffold";
    }

    @Override
    public String displayName() {
        return "Scaffold typed form beans from Struts form-bean definitions";
    }

    @Override
    public Optional<FileChange> transform(String relativePath, String content) {
        return Optional.empty();
    }

    private String inferDefaultPackage(Path projectRoot) throws IOException {
        try (var walk = Files.walk(projectRoot.resolve("src/main/java"))) {
            return walk.filter(Files::isRegularFile)
                    .filter(p -> p.toString().endsWith("Action.java"))
                    .findFirst()
                    .map(this::packageFromFile)
                    .orElse("com.example.forms");
        } catch (IOException ex) {
            return "com.example.forms";
        }
    }

    private String packageFromFile(Path javaFile) {
        try {
            String content = Files.readString(javaFile);
            int pkg = content.indexOf("package ");
            if (pkg < 0) {
                return "com.example.forms";
            }
            int semi = content.indexOf(';', pkg);
            return content.substring(pkg + 8, semi).trim();
        } catch (IOException ex) {
            return "com.example.forms";
        }
    }

    private String resolveFqcn(StrutsMappingIndex.FormBean bean, String defaultPackage) {
        if (bean.type().contains(".") && !bean.type().contains("DynaActionForm")) {
            return bean.type();
        }
        return defaultPackage + "." + StrutsMappingIndex.inferFormClassName(bean.name());
    }

    private String fqcnToRelativePath(String fqcn) {
        return "src/main/java/" + fqcn.replace('.', '/') + ".java";
    }

    private String generateSource(
            String fqcn,
            String formName,
            List<StrutsValidationIndex.ValidationField> fields) {
        int dot = fqcn.lastIndexOf('.');
        String pkg = dot >= 0 ? fqcn.substring(0, dot) : "";
        String className = dot >= 0 ? fqcn.substring(dot + 1) : fqcn;
        boolean needsNotNull = fields.stream().anyMatch(f -> f.hasRule("required"));
        boolean needsEmail = fields.stream().anyMatch(f -> f.hasRule("email"));

        StringBuilder sb = new StringBuilder();
        if (!pkg.isBlank()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        if (needsNotNull) {
            sb.append("import jakarta.validation.constraints.NotNull;\n");
        }
        if (needsEmail) {
            sb.append("import jakarta.validation.constraints.Email;\n");
        }
        if (needsNotNull || needsEmail) {
            sb.append("\n");
        }
        sb.append("""
                // Generated by UpGrd from Struts form-bean '%s' and validation.xml
                public class %s {
                """.formatted(formName, className));
        for (StrutsValidationIndex.ValidationField field : fields) {
            sb.append(fieldAnnotations(field));
            sb.append("    private String ").append(field.property()).append(";\n\n");
        }
        for (StrutsValidationIndex.ValidationField field : fields) {
            String prop = field.property();
            String cap = Character.toUpperCase(prop.charAt(0)) + prop.substring(1);
            sb.append("""
                        public String get%s() {
                            return %s;
                        }

                        public void set%s(String %s) {
                            this.%s = %s;
                        }

                    """.formatted(cap, prop, cap, prop, prop, prop));
        }
        sb.append("}\n");
        return sb.toString();
    }

    private String fieldAnnotations(StrutsValidationIndex.ValidationField field) {
        StringBuilder annotations = new StringBuilder();
        if (field.hasRule("required")) {
            annotations.append("    @NotNull\n");
        }
        if (field.hasRule("email")) {
            annotations.append("    @Email\n");
        }
        return annotations.toString();
    }
}
