package com.upgrd.core.documentation;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.upgrd.core.model.ApplicationDocumentation;
import com.upgrd.core.model.DocumentationSection;
import com.upgrd.core.model.SecurityReport;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public final class DocumentationWriter {

    private final ObjectMapper mapper = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .enable(SerializationFeature.INDENT_OUTPUT);

    public Path write(ApplicationDocumentation documentation, Path outputDir) throws IOException {
        Files.createDirectories(outputDir);
        Path json = outputDir.resolve("app-documentation.json");
        mapper.writeValue(json.toFile(), documentation);
        Files.writeString(outputDir.resolve("AGENTS.md"), renderMarkdown(documentation));
        return json;
    }

    private String renderMarkdown(ApplicationDocumentation doc) {
        StringBuilder md = new StringBuilder();
        md.append("# Application Documentation (UpGrd)\n\n");
        md.append("> ").append(doc.summary()).append("\n\n");
        md.append("- **Profile:** ").append(doc.profile()).append("\n");
        md.append("- **Source:** `").append(doc.sourceRoot()).append("`\n");
        md.append("- **Generated:** ").append(doc.generatedAt()).append("\n\n");

        md.append("## Report Index\n\n");
        for (String report : doc.reportIndex()) {
            md.append("- `").append(report).append("`\n");
        }
        md.append("\n");

        for (DocumentationSection section : doc.sections()) {
            md.append("## ").append(section.title()).append("\n\n");
            md.append("_Phase: ").append(section.phase())
                    .append(" | Category: ").append(section.category()).append("_\n\n");
            md.append(section.content()).append("\n\n");
            if (!section.relatedFiles().isEmpty()) {
                md.append("Related: ");
                md.append(String.join(", ", section.relatedFiles().stream()
                        .map(f -> "`" + f + "`").toList()));
                md.append("\n\n");
            }
        }

        md.append("---\n");
        md.append("Generated by UpGrd for edge-local, agent-readable analysis. No cloud upload.\n");
        return md.toString();
    }
}
