package com.upgrd.core.apply;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates server-specific deployment overlays under {@code deploy/wildfly} and {@code deploy/weblogic}.
 * Portable application code stays in {@code app-web/}; bindings differ per environment.
 */
public final class DeployProfileScaffolder {

    public List<String> scaffoldWildFly(Path migratedRoot, String appContext) throws IOException {
        Path deployDir = migratedRoot.resolve("deploy/wildfly");
        Files.createDirectories(deployDir);

        String context = appContext == null || appContext.isBlank() ? "app-web" : appContext;
        List<String> artifacts = new ArrayList<>();

        write(deployDir.resolve("README.md"), wildflyReadme(context), artifacts);
        write(deployDir.resolve("docker-compose.yml"), wildflyDockerCompose(), artifacts);
        write(deployDir.resolve("jboss-web.xml"), jbossWebXml(context), artifacts);
        write(deployDir.resolve("deploy.sh"), wildflyDeployScript(context), artifacts);
        return artifacts;
    }

    public List<String> scaffoldWebLogic(Path migratedRoot, String productionServer) throws IOException {
        Path deployDir = migratedRoot.resolve("deploy/weblogic");
        Files.createDirectories(deployDir);

        String server = productionServer == null || productionServer.isBlank() ? "weblogic-14c" : productionServer;
        List<String> artifacts = new ArrayList<>();

        write(deployDir.resolve("README.md"), weblogicReadme(server), artifacts);
        write(deployDir.resolve("weblogic.xml"), weblogicXml(), artifacts);
        write(deployDir.resolve("weblogic-application.xml"), weblogicApplicationXml(), artifacts);
        write(deployDir.resolve("deploy.sh"), weblogicDeployScript(server), artifacts);
        write(deployDir.resolve("wldeploy.properties"), wldeployProperties(server), artifacts);
        write(deployDir.resolve("wldeploy.sh"), wldeployScript(server), artifacts);
        return artifacts;
    }

    private void write(Path file, String content, List<String> artifacts) throws IOException {
        Files.writeString(file, content);
        artifacts.add("deploy/" + file.getParent().getFileName() + "/" + file.getFileName());
    }

    private String wildflyReadme(String context) {
        return """
                # WildFly local deployment (UpGrd)

                Use this profile for **local verification** before production WebLogic deploy.

                ## Quick start

                ```bash
                # From migrated/ root (or use UpGrd CLI)
                mvn -Plocal-wildfly package
                upgrd wildfly start --output ../upgrd-out
                upgrd wildfly deploy --output ../upgrd-out
                ```

                Context root: `/""" + context + """
                `

                JNDI bindings for datasources belong in `standalone.xml` or CLI scripts — not in portable Java code.
                """;
    }

    private String wildflyDockerCompose() {
        return """
                # Generated by UpGrd — local WildFly for edge verification
                services:
                  wildfly:
                    container_name: upgrd-wildfly
                    image: quay.io/wildfly/wildfly:34.0.0.Final-jdk21
                    ports:
                      - "8080:8080"
                      - "9990:9990"
                    volumes:
                      - ./deployments:/opt/jboss/wildfly/standalone/deployments
                    environment:
                      - WILDFLY_ADMIN=admin
                      - WILDFLY_ADMIN_PASSWORD=admin
                """;
    }

    private String jbossWebXml(String context) {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd wildfly-local -->
                <jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://www.jboss.org/schema/jbossas/jboss-web_14_0.xsd"
                           version="14.0">
                  <context-root>""" + context + """
                </context-root>
                </jboss-web>
                """;
    }

    private String wildflyDeployScript(String context) {
        return """
                #!/bin/sh
                # Generated by UpGrd — deploy WAR to local WildFly (prefer: upgrd wildfly deploy)
                set -e
                WAR="../app-web/target/app-web-1.0.0-SNAPSHOT.war"
                DEST="./deployments/app-web.war"
                if [ ! -f "$WAR" ]; then
                  echo "Build WAR first: mvn -Plocal-wildfly package"
                  exit 1
                fi
                mkdir -p deployments
                cp "$WAR" "$DEST"
                echo "Copied WAR to $DEST (context /%s)"
                echo "If container is running with volume mount, WildFly will auto-deploy."
                """.formatted(context);
    }

    private String weblogicReadme(String server) {
        return """
                # WebLogic production deployment (UpGrd)

                Production target: **%s**

                ## Build for WebLogic

                ```bash
                mvn -Pproduction-weblogic package
                ```

                Copy descriptors from this directory alongside the WAR when deploying to WebLogic.
                Keep `weblogic.*` imports out of portable business code.

                ## wldeploy (WebLogic 14c)

                Configure credentials via environment variables (see `wldeploy.properties`), then:

                ```bash
                mvn -Pproduction-weblogic package
                ./deploy/weblogic/wldeploy.sh
                ```

                Undeploy: `./deploy/weblogic/wldeploy.sh undeploy`
                """.formatted(server);
    }

    private String weblogicXml() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd weblogic-adapters -->
                <weblogic-web-app xmlns="http://xmlns.oracle.com/weblogic/weblogic-web-app"
                                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                  xsi:schemaLocation="http://xmlns.oracle.com/weblogic/weblogic-web-app
                                  http://xmlns.oracle.com/weblogic/weblogic-web-app/1.9/weblogic-web-app.xsd">
                  <context-root>app-web</context-root>
                  <container-descriptor>
                    <prefer-application-packages>
                      <package-name>org.slf4j.*</package-name>
                    </prefer-application-packages>
                  </container-descriptor>
                </weblogic-web-app>
                """;
    }

    private String weblogicApplicationXml() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd weblogic-adapters -->
                <weblogic-application xmlns="http://xmlns.oracle.com/weblogic/weblogic-application"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:schemaLocation="http://xmlns.oracle.com/weblogic/weblogic-application
                                      http://xmlns.oracle.com/weblogic/weblogic-application/1.9/weblogic-application.xsd">
                  <application-name>migrated-app-web</application-name>
                  <prefer-application-packages>
                    <package-name>org.slf4j.*</package-name>
                  </prefer-application-packages>
                </weblogic-application>
                """;
    }

    private String weblogicDeployScript(String server) {
        return """
                #!/bin/sh
                # Generated by UpGrd — WebLogic deploy helper (%s)
                set -e
                WAR="../app-web/target/app-web-1.0.0-SNAPSHOT.war"
                if [ ! -f "$WAR" ]; then
                  echo "Build WAR first: mvn -Pproduction-weblogic package"
                  exit 1
                fi
                echo "Deploy $WAR to WebLogic — use wldeploy.sh or console; customize for %s."
                """.formatted(server, server);
    }

    private String wldeployProperties(String server) {
        return """
                # Generated by UpGrd — WebLogic wldeploy settings (%s)
                # Export these environment variables before running wldeploy.sh (never commit secrets):
                #
                # WLS_ADMIN_URL=t3://localhost:7001
                # WLS_USER=weblogic
                # WLS_PASSWORD=changeme
                # WLS_TARGETS=AdminServer
                # WLS_APP_NAME=app-web
                #
                app.name=app-web
                war.path=../app-web/target/app-web-1.0.0-SNAPSHOT.war
                """.formatted(server);
    }

    private String wldeployScript(String server) {
        return """
                #!/bin/sh
                # Generated by UpGrd — WebLogic wldeploy helper (%s)
                # Requires weblogic.jar / WL_HOME on classpath for weblogic.Deployer
                set -e
                SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

                ADMIN_URL="${WLS_ADMIN_URL:-t3://localhost:7001}"
                WLS_USER="${WLS_USER:-weblogic}"
                WLS_PASSWORD="${WLS_PASSWORD:-changeme}"
                WLS_TARGETS="${WLS_TARGETS:-AdminServer}"
                WLS_APP_NAME="${WLS_APP_NAME:-app-web}"
                WAR="${SCRIPT_DIR}/../app-web/target/app-web-1.0.0-SNAPSHOT.war"

                if [ ! -f "$WAR" ]; then
                  echo "Build WAR first: mvn -Pproduction-weblogic package"
                  exit 1
                fi

                ACTION="${1:-deploy}"
                if [ "$ACTION" = "undeploy" ]; then
                  echo "Undeploying $WLS_APP_NAME from $ADMIN_URL"
                  java weblogic.Deployer -adminurl "$ADMIN_URL" -username "$WLS_USER" -password "$WLS_PASSWORD" \\
                    -undeploy -name "$WLS_APP_NAME" -targets "$WLS_TARGETS"
                  exit 0
                fi

                echo "Deploying $WAR as $WLS_APP_NAME to $WLS_TARGETS on $ADMIN_URL"
                java weblogic.Deployer -adminurl "$ADMIN_URL" -username "$WLS_USER" -password "$WLS_PASSWORD" \\
                  -deploy -name "$WLS_APP_NAME" -source "$WAR" -targets "$WLS_TARGETS" -nostage
                """.formatted(server);
    }
}
