package com.upgrd.core.apply;

import com.upgrd.core.model.ProjectProfile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates a starter Maven POM for migrated projects.
 */
public final class MavenScaffolder {

    public void scaffold(Path migratedRoot, ProjectProfile profile, String targetJava) throws IOException {
        String javaVersion = targetJava.replace("java", "");
        Path pom = migratedRoot.resolve("pom.xml");
        Path appPom = migratedRoot.resolve("app-web/pom.xml");

        Files.createDirectories(migratedRoot.resolve("app-web"));
        Files.writeString(pom, parentPom(javaVersion, profile));
        Files.writeString(appPom, webModulePom(javaVersion, profile));
    }

    private String parentPom(String javaVersion, ProjectProfile profile) {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd convert-maven -->
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.example.migrated</groupId>
                  <artifactId>migrated-parent</artifactId>
                  <version>1.0.0-SNAPSHOT</version>
                  <packaging>pom</packaging>
                  <modules>
                    <module>app-web</module>
                  </modules>
                  <properties>
                    <maven.compiler.release>%s</maven.compiler.release>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                  </properties>
                </project>
                """.formatted(javaVersion);
    }

    private String webModulePom(String javaVersion, ProjectProfile profile) {
        String deps = profile == ProjectProfile.LEGACY_WEB ? webDependencies() : backendDependencies();
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!-- Generated by UpGrd convert-maven -->
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                  <parent>
                    <groupId>com.example.migrated</groupId>
                    <artifactId>migrated-parent</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                  </parent>
                  <artifactId>app-web</artifactId>
                  <packaging>%s</packaging>
                  <dependencies>
                %s
                  </dependencies>
                </project>
                """.formatted(
                profile == ProjectProfile.LEGACY_WEB ? "war" : "jar",
                deps);
    }

    private String webDependencies() {
        return """
                        <dependency>
                          <groupId>org.slf4j</groupId>
                          <artifactId>slf4j-api</artifactId>
                          <version>2.0.16</version>
                        </dependency>
                        <dependency>
                          <groupId>jakarta.servlet</groupId>
                          <artifactId>jakarta.servlet-api</artifactId>
                          <version>6.0.0</version>
                          <scope>provided</scope>
                        </dependency>
                    """;
    }

    private String backendDependencies() {
        return """
                        <dependency>
                          <groupId>org.slf4j</groupId>
                          <artifactId>slf4j-api</artifactId>
                          <version>2.0.16</version>
                        </dependency>
                    """;
    }
}
