package com.upgrd.core.apply;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Scaffolds OpenRewrite configuration for future AST-based migrations (M5+).
 */
public final class OpenRewriteScaffolder {

    public List<String> scaffold(Path migratedRoot, String targetJava) throws IOException {
        Path upgrdDir = migratedRoot.resolve(".upgrd");
        Files.createDirectories(upgrdDir);

        Path config = upgrdDir.resolve("openrewrite.yml");
        Files.writeString(config, openRewriteYaml(targetJava));
        Path readme = upgrdDir.resolve("OPENREWRITE.md");
        Files.writeString(readme, readme());

        return List.of(".upgrd/openrewrite.yml", ".upgrd/OPENREWRITE.md");
    }

    private String openRewriteYaml(String targetJava) {
        String javaRecipe = targetJava.replace("java", "");
        return """
                # Generated by UpGrd — run with OpenRewrite Maven plugin when ready for AST migrations
                type: specs
                specs:
                  - type: specs.openrewrite.org/v1beta/recipe
                    name: com.upgrd.migrated.UpgradeBaseline
                    displayName: UpGrd migrated app baseline
                    recipeList:
                      - org.openrewrite.java.migrate.UpgradeToJava%s
                      - org.openrewrite.java.spring.framework.UpgradeSpringFramework_6_0
                      - org.openrewrite.staticanalysis.CommonStaticAnalysis
                      - org.openrewrite.staticanalysis.ExternalizableHasNoArgsConstructor
                      - org.openrewrite.staticanalysis.NoDoubleBraceInitialization
                """.formatted(javaRecipe);
    }

    private String readme() {
        return """
                # OpenRewrite integration (UpGrd M5+)

                UpGrd applies safe file-level recipes during `apply`. For deeper AST migrations run:

                ```bash
                upgrd rewrite run --output ../upgrd-out
                upgrd rewrite run --output ../upgrd-out --dry-run
                ```

                Or via Maven directly:

                ```bash
                mvn org.openrewrite.maven:rewrite-maven-plugin:run \\
                  -Drewrite.activeRecipes=com.upgrd.migrated.UpgradeBaseline
                ```

                Recipe list is defined in `.upgrd/openrewrite.yml`. UpGrd-native recipes take precedence for
                edge-local apply; OpenRewrite complements them for complex refactors.
                """;
    }
}
