package com.upgrd.core.apply;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * Wires Thymeleaf + Spring MVC when UpGrd scaffolds HTML templates from Struts JSPs.
 */
public final class ThymeleafScaffolder {

    private static final String THYMELEAF_MARKER = "thymeleaf-spring6";
    private static final String CONFIG_CLASS = "WebMvcThymeleafConfig.java";

    public List<String> scaffold(Path appWebRoot) throws IOException {
        Path templatesDir = appWebRoot.resolve("src/main/resources/templates");
        if (!hasThymeleafTemplates(templatesDir)) {
            return List.of();
        }

        List<String> artifacts = new ArrayList<>();
        patchAppPom(appWebRoot);
        artifacts.add("app-web/pom.xml (Thymeleaf deps)");

        Path configDir = appWebRoot.resolve("src/main/java/com/example/config");
        Files.createDirectories(configDir);
        Path config = configDir.resolve(CONFIG_CLASS);
        if (!Files.isRegularFile(config)) {
            Files.writeString(config, webMvcThymeleafConfig());
            artifacts.add("app-web/src/main/java/com/example/config/" + CONFIG_CLASS);
        }
        return artifacts;
    }

    private boolean hasThymeleafTemplates(Path templatesDir) throws IOException {
        if (!Files.isDirectory(templatesDir)) {
            return false;
        }
        try (Stream<Path> walk = Files.walk(templatesDir)) {
            return walk.anyMatch(p -> p.toString().endsWith(".html"));
        }
    }

    private void patchAppPom(Path appWebRoot) throws IOException {
        Path pom = appWebRoot.resolve("pom.xml");
        String content = Files.readString(pom);
        if (content.contains(THYMELEAF_MARKER)) {
            return;
        }
        String deps = """
                        <dependency>
                          <groupId>org.thymeleaf</groupId>
                          <artifactId>thymeleaf-spring6</artifactId>
                          <version>3.1.3.RELEASE</version>
                        </dependency>
                        <dependency>
                          <groupId>org.hibernate.validator</groupId>
                          <artifactId>hibernate-validator</artifactId>
                          <version>8.0.2.Final</version>
                        </dependency>
                        <dependency>
                          <groupId>jakarta.validation</groupId>
                          <artifactId>jakarta.validation-api</artifactId>
                          <version>3.0.2</version>
                        </dependency>
                """;
        Files.writeString(pom, content.replace("  </dependencies>", deps + "  </dependencies>"));
    }

    private String webMvcThymeleafConfig() {
        return """
                package com.example.config;

                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.ComponentScan;
                import org.springframework.context.annotation.Configuration;
                import org.springframework.web.servlet.config.annotation.EnableWebMvc;
                import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
                import org.thymeleaf.spring6.SpringTemplateEngine;
                import org.thymeleaf.spring6.templateresolver.SpringResourceTemplateResolver;
                import org.thymeleaf.spring6.view.ThymeleafViewResolver;

                /**
                 * Generated by UpGrd — Thymeleaf view resolver for migrated Struts JSPs.
                 */
                @Configuration
                @EnableWebMvc
                @ComponentScan("com.example")
                public class WebMvcThymeleafConfig implements WebMvcConfigurer {

                    @Bean
                    public SpringResourceTemplateResolver templateResolver() {
                        SpringResourceTemplateResolver resolver = new SpringResourceTemplateResolver();
                        resolver.setPrefix("classpath:/templates/");
                        resolver.setSuffix(".html");
                        resolver.setTemplateMode("HTML");
                        resolver.setCharacterEncoding("UTF-8");
                        return resolver;
                    }

                    @Bean
                    public SpringTemplateEngine templateEngine(SpringResourceTemplateResolver templateResolver) {
                        SpringTemplateEngine engine = new SpringTemplateEngine();
                        engine.setTemplateResolver(templateResolver);
                        engine.setEnableSpringELCompiler(true);
                        return engine;
                    }

                    @Bean
                    public ThymeleafViewResolver viewResolver(SpringTemplateEngine templateEngine) {
                        ThymeleafViewResolver resolver = new ThymeleafViewResolver();
                        resolver.setTemplateEngine(templateEngine);
                        resolver.setCharacterEncoding("UTF-8");
                        return resolver;
                    }
                }
                """;
    }
}
