package com.upgrd.core.export;

import com.upgrd.core.model.AuditExport;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generates a compliance-oriented PDF summary from the audit bundle.
 */
public final class AuditPdfExporter {

    private static final float MARGIN = 50;
    private static final float LINE_HEIGHT = 14;
    private static final int MAX_LINES_PER_PAGE = 48;

    public Path export(AuditExport bundle, Path outputDir) throws IOException {
        Path pdf = outputDir.resolve("audit-export.pdf");
        List<String> lines = buildLines(bundle);

        try (PDDocument document = new PDDocument()) {
            PDType1Font font = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            PDType1Font fontBold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            int index = 0;
            while (index < lines.size()) {
                PDPage page = new PDPage(PDRectangle.LETTER);
                document.addPage(page);
                try (PDPageContentStream stream = new PDPageContentStream(document, page)) {
                    float y = page.getMediaBox().getHeight() - MARGIN;
                    int linesOnPage = 0;
                    while (index < lines.size() && linesOnPage < MAX_LINES_PER_PAGE) {
                        String line = sanitize(lines.get(index));
                        if (line.startsWith("## ")) {
                            stream.setFont(fontBold, 12);
                            line = line.substring(3);
                        } else {
                            stream.setFont(font, 10);
                        }
                        stream.beginText();
                        stream.newLineAtOffset(MARGIN, y);
                        stream.showText(truncate(line, 95));
                        stream.endText();
                        y -= LINE_HEIGHT;
                        index++;
                        linesOnPage++;
                    }
                }
            }
            document.save(pdf.toFile());
        }
        return pdf;
    }

    private List<String> buildLines(AuditExport bundle) {
        List<String> lines = new ArrayList<>();
        lines.add("UpGrd Audit Export");
        lines.add("Generated: " + bundle.exportedAt());
        lines.add("Version: " + bundle.upgrdVersion());
        lines.add("Output: " + bundle.outputDirectory());
        lines.add("Reports included: " + bundle.includedReports().size());
        lines.add("");

        for (Map.Entry<String, Object> entry : bundle.reports().entrySet()) {
            lines.add("## " + entry.getKey());
            for (String line : String.valueOf(entry.getValue()).split("\\R")) {
                if (!line.isBlank()) {
                    lines.add("  " + line.trim());
                }
                if (lines.size() > 400) {
                    lines.add("  ... (truncated for PDF summary)");
                    return lines;
                }
            }
            lines.add("");
        }
        lines.add("Edge-local audit — generated by UpGrd without cloud upload.");
        return lines;
    }

    private String sanitize(String line) {
        return line.replace('\t', ' ')
                .chars()
                .filter(ch -> ch >= 32 && ch <= 126)
                .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
                .toString();
    }

    private String truncate(String line, int max) {
        return line.length() <= max ? line : line.substring(0, max - 3) + "...";
    }
}
